name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: go test
        run: make test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID_DEV }}:role/githubOIDCCDKDeployerRole
          role-session-name: githubOIDCCDKDeployerRole

      - run: aws sts get-caller-identity

      - name: install npm
        run: 'sudo apt update -y && sudo apt install nodejs npm -y'

      - name: install AWS CDK
        run: 'sudo npm install -g aws-cdk'

      - name: Build lambda and deploy
        run: |
          make build

      - name: cdk deploy
        run: cdk synth
        working-directory: deploy/aws-cdk/shortener
